### ISSUE TITLE
is there a solution to code.google https://code.google.com/p/tabplotd3/issues/detail?id=1?

### ISSUE THREAD

**Issue by timelyportfolio** [edwindj/tabplotd3#1]
Is there a solution to code.google https://code.google.com/p/tabplotd3/issues/detail?id=1?  I get the same error in Windows with 

> sessionInfo()
> R version 3.0.1 (2013-05-16)
> Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] grid      tools     stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
[1] brew_1.0-6    tabplotd3_0.2 tabplot_1.0   ffbase_0.9    ff_2.2-11  
[6] bit_1.1-10    RJSONIO_1.0-3 Rook_1.1-0    devtools_1.3 

loaded via a namespace (and not attached):
[1] digest_0.6.3   evaluate_0.4.4 httr_0.2       memoise_0.1    parallel_3.0.1
[6] RCurl_1.95-4.1 stringr_0.6.2  whisker_0.3-2

**Comment by edwindj** [comment]
I will look into the problem this weekend, please note that the source code
has been moved to github: http://github.com/edwindj/tabplotd3

Best regards,

Edwin

2013/8/30 timelyportfolio notifications@github.com

**Comment by timelyportfolio** [comment]
Oh great.  I will continue to try to debug today.  For reference, the Rook code in http://lamages.blogspot.com/2012/08/rook-rocks-example-with-googlevis.html works fine on my machine.

**Comment by timelyportfolio** [comment]
### Redirect is a Rook Issue

This appears to be a Rook problem that has not been reported (as far as I can find).  I hacked a crude version that proves that the issues is not with tabplotd3.  Just in case you or someone else wants to see my ugly code, I will paste it below.

``` r
require(tabplotd3)

### think this fixes an error in the sort
### think also fixes categorical variables
adjust_fixsort <- function(tp){
  atp <- list()
  varnms <- sapply(tp$columns, function(i) i$name)
  vars <- lapply( 
    tp$columns,
    function(i) {
      if (i$isnumeric)
        return(list(
          mean = i$mean,
          compl = i$compl/100
        ) )
      #####////////////// here is the fix ////////#############################################
      categories <- i$categories
      freq <- round(i$freq / rowSums(i$freq), 4)
      colnames(freq) <- NULL
      list( freq = freq, palet=i$palet, categories=categories)                                  
    }
  )
  names(vars) <- varnms
  atp$vars <- vars
  #   atp$dataset <- tp$dataset
  #####////////////// here is the fix ////////#############################################
  atp$sortCol <- unlist(lapply(tp$columns, function(x) if (!is.na(x$sort_decreasing)) x$name))
  atp$nBins <- tp$nBins
  atp
}

#### set this up to call the fixed adjust_fixsort function instead of adjust
tpjson_fixsort <- function(env){
  req <- Request$new(env)
  res <- Response$new()
  res$header('Content-type','application/json')

  params <- req$params()
  #print(params)


  if ("dat" %in% names(params)){
    params[["dat"]] <- eval(as.name(params[["dat"]]), envir=.GlobalEnv)

    nums <- match(c("from", "to", "nBins"), names(params), nomatch=0)
    #print(list(nums=nums, params=params))
    params[nums] <- lapply(params[nums], as.numeric)
    params["decreasing"] <- !params["decreasing"] %in% c("false")
    params[["plot"]] <- FALSE
    #print(params)
    tp <- do.call(tableplot, params)
    res$write(toJSON(adjust_fixsort(tp)))
  }  else {
    dmp <- list(params=params)
    res$write(toJSON(tp))
  }
  res$finish()
}



s <- Rhttpd$new()

data(diamonds,package="ggplot2")

itabplot.custom <- function  (x, ...) 
{
  require(brew)

  xlit <- deparse(substitute(x))

  tp <- toJSON(adjust_fixsort(tableplot(x, plot = FALSE)))

  if (is.null(s)){
    s <- Rhttpd$new()
  } else { 
    s$remove(all=TRUE)
  }

  app <- Builder$new(
    URLMap$new( 
      '^/json' = tpjson_fixsort,
      '^/.*\\.html$' = function(env){
        body <- paste(capture.output(brew("index_template.html")),collapse="\n")
        req <- Request$new(env)
        res <- Response$new()
        res$write(body)
        res$finish()
      },
      '^/.*\\.css$' = File$new(root = system.file("app", package="tabplotd3")),
      '^/.*\\.js$'= File$new(root = system.file("app", package="tabplotd3")),
      '^/.*\\.png$'= File$new(root = ".")
    )
  )

  s$launch(app=app, name="tabplotd3")
}

itabplot.custom(diamonds)
```

### Another Issue

 However, I do get what I think is an unrelated bug from tpjson.  I will report that in a separate issue, but you can also see the changes in the code above in `adjust_fixsort` and `tpjson_fixsort`.
