### ISSUE TITLE
sort piece of adjust seemingly messed up so tpjson not working correctly

### ISSUE THREAD

**Issue by timelyportfolio** [edwindj/tabplotd3#2]
Not sure if `tableplot` structure changed or not, but the `adjust` function is not working for me.  I made this change to fix it:

```
atp$sortCol <- unlist(lapply(tp$columns, function(x) if (!is.na(x$sort_decreasing)) x$name))
```

**Comment by edwindj** [comment]
tableplot structure has changed: I will adjust tabplotd3 shortly.

**Comment by edwindj** [comment]
Should work now

**Comment by timelyportfolio** [comment]
great, I confirm it works.  Thanks.
